ALTER TABLE calls ADD COLUMN IF NOT EXISTS ofs_status text;

CREATE TABLE IF NOT EXISTS d0_base_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name text NOT NULL,
  row_number integer NOT NULL,
  payload jsonb NOT NULL,
  uploaded_by text NOT NULL,
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS d0_base_records_imported_idx ON d0_base_records(imported_at DESC);