ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS ofs_status text;

CREATE TABLE IF NOT EXISTS public.d0_base_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name text NOT NULL,
  row_number integer NOT NULL,
  payload jsonb NOT NULL,
  uploaded_by text NOT NULL,
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS d0_base_records_imported_idx ON public.d0_base_records(imported_at DESC);
ALTER TABLE public.d0_base_records ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.d0_base_records TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.d0_base_records_id_seq TO service_role;